// values from <sys/socket.h>, <linux/rtnetlink.h>, <linux/if_link.h>, <linux/if_addr.h>, <linux/if.h> and <linux/netlink.h>

// address families, used as ifi_family
const AF_UNSPEC = 0n;
const AF_PACKET = 17n;
const AF_INET = 2n;
const AF_INET6 = 10n;

// rtnetlink message types for links
const RTM_NEWLINK = 16n;
const RTM_DELLINK = 17n;
const RTM_GETLINK = 18n;
const RTM_SETLINK = 19n;

// rtnetlink message types for addresses
const RTM_NEWADDR = 20n;
const RTM_DELADDR = 21n;
const RTM_GETADDR = 22n;

// multicast group for link notifications, to be bound as nl_groups
const RTMGRP_LINK = 1n;
const RTMGRP_IPV4_IFADDR = 0x10n;
const RTMGRP_IPV6_IFADDR = 0x100n;

// link attributes
const IFLA_UNSPEC = 0n;
const IFLA_ADDRESS = 1n;
const IFLA_BROADCAST = 2n;
const IFLA_IFNAME = 3n;
const IFLA_MTU = 4n;
const IFLA_LINK = 5n;
const IFLA_QDISC = 6n;
const IFLA_STATS = 7n;
const IFLA_MASTER = 10n;
const IFLA_TXQLEN = 13n;
const IFLA_OPERSTATE = 16n;
const IFLA_LINKMODE = 17n;
const IFLA_LINKINFO = 18n;
const IFLA_NET_NS_PID = 19n;
const IFLA_IFALIAS = 20n;
const IFLA_GROUP = 27n;
const IFLA_NET_NS_FD = 28n;

// nested attributes of IFLA_LINKINFO
const IFLA_INFO_UNSPEC = 0n;
const IFLA_INFO_KIND = 1n;
const IFLA_INFO_DATA = 2n;
const IFLA_INFO_XSTATS = 3n;
const IFLA_INFO_SLAVE_KIND = 4n;
const IFLA_INFO_SLAVE_DATA = 5n;

// nested attributes of IFLA_INFO_DATA for macvlan and macvtap links
const IFLA_MACVLAN_UNSPEC = 0n;
const IFLA_MACVLAN_MODE = 1n;
const IFLA_MACVLAN_FLAGS = 2n;

// values of IFLA_MACVLAN_MODE
const MACVLAN_MODE_PRIVATE = 1n;
const MACVLAN_MODE_VEPA = 2n;
const MACVLAN_MODE_BRIDGE = 4n;
const MACVLAN_MODE_PASSTHRU = 8n;
const MACVLAN_MODE_SOURCE = 16n;

// address attributes
const IFA_UNSPEC = 0n;
const IFA_ADDRESS = 1n;
const IFA_LOCAL = 2n;
const IFA_LABEL = 3n;
const IFA_BROADCAST = 4n;
const IFA_ANYCAST = 5n;
const IFA_CACHEINFO = 6n;
const IFA_MULTICAST = 7n;
const IFA_FLAGS = 8n;
const IFA_RT_PRIORITY = 9n;
const IFA_TARGET_NETNSID = 10n;

// address flags, the lower 8 bits in ifa_flags, all of them in IFA_FLAGS
const IFA_F_SECONDARY = 0x01n;
const IFA_F_TEMPORARY = 0x01n;
const IFA_F_NODAD = 0x02n;
const IFA_F_OPTIMISTIC = 0x04n;
const IFA_F_DADFAILED = 0x08n;
const IFA_F_HOMEADDRESS = 0x10n;
const IFA_F_DEPRECATED = 0x20n;
const IFA_F_TENTATIVE = 0x40n;
const IFA_F_PERMANENT = 0x80n;
const IFA_F_MANAGETEMPADDR = 0x100n;
const IFA_F_NOPREFIXROUTE = 0x200n;
const IFA_F_MCAUTOJOIN = 0x400n;
const IFA_F_STABLE_PRIVACY = 0x800n;

// scopes of addresses, ifa_scope
const RT_SCOPE_UNIVERSE = 0n;
const RT_SCOPE_SITE = 200n;
const RT_SCOPE_LINK = 253n;
const RT_SCOPE_HOST = 254n;
const RT_SCOPE_NOWHERE = 255n;

// flags of an rtattr type
const NLA_F_NESTED = 0x8000n;
const NLA_F_NET_BYTEORDER = 0x4000n;
const NLA_TYPE_MASK = 0x3FFFn;

// link flags, ifi_flags and ifi_change
const IFF_UP = 0x1n;
const IFF_BROADCAST = 0x2n;
const IFF_DEBUG = 0x4n;
const IFF_LOOPBACK = 0x8n;
const IFF_POINTOPOINT = 0x10n;
const IFF_NOTRAILERS = 0x20n;
const IFF_RUNNING = 0x40n;
const IFF_NOARP = 0x80n;
const IFF_PROMISC = 0x100n;
const IFF_ALLMULTI = 0x200n;
const IFF_MASTER = 0x400n;
const IFF_SLAVE = 0x800n;
const IFF_MULTICAST = 0x1000n;
const IFF_PORTSEL = 0x2000n;
const IFF_AUTOMEDIA = 0x4000n;
const IFF_DYNAMIC = 0x8000n;
const IFF_LOWER_UP = 0x10000n;
const IFF_DORMANT = 0x20000n;
const IFF_ECHO = 0x40000n;

export {
  AF_UNSPEC,
  AF_PACKET,
  AF_INET,
  AF_INET6,

  RTM_NEWLINK,
  RTM_DELLINK,
  RTM_GETLINK,
  RTM_SETLINK,

  RTM_NEWADDR,
  RTM_DELADDR,
  RTM_GETADDR,

  RTMGRP_LINK,
  RTMGRP_IPV4_IFADDR,
  RTMGRP_IPV6_IFADDR,

  IFLA_UNSPEC,
  IFLA_ADDRESS,
  IFLA_BROADCAST,
  IFLA_IFNAME,
  IFLA_MTU,
  IFLA_LINK,
  IFLA_QDISC,
  IFLA_STATS,
  IFLA_MASTER,
  IFLA_TXQLEN,
  IFLA_OPERSTATE,
  IFLA_LINKMODE,
  IFLA_LINKINFO,
  IFLA_NET_NS_PID,
  IFLA_IFALIAS,
  IFLA_GROUP,
  IFLA_NET_NS_FD,

  IFLA_INFO_UNSPEC,
  IFLA_INFO_KIND,
  IFLA_INFO_DATA,
  IFLA_INFO_XSTATS,
  IFLA_INFO_SLAVE_KIND,
  IFLA_INFO_SLAVE_DATA,

  IFLA_MACVLAN_UNSPEC,
  IFLA_MACVLAN_MODE,
  IFLA_MACVLAN_FLAGS,

  MACVLAN_MODE_PRIVATE,
  MACVLAN_MODE_VEPA,
  MACVLAN_MODE_BRIDGE,
  MACVLAN_MODE_PASSTHRU,
  MACVLAN_MODE_SOURCE,

  IFA_UNSPEC,
  IFA_ADDRESS,
  IFA_LOCAL,
  IFA_LABEL,
  IFA_BROADCAST,
  IFA_ANYCAST,
  IFA_CACHEINFO,
  IFA_MULTICAST,
  IFA_FLAGS,
  IFA_RT_PRIORITY,
  IFA_TARGET_NETNSID,

  IFA_F_SECONDARY,
  IFA_F_TEMPORARY,
  IFA_F_NODAD,
  IFA_F_OPTIMISTIC,
  IFA_F_DADFAILED,
  IFA_F_HOMEADDRESS,
  IFA_F_DEPRECATED,
  IFA_F_TENTATIVE,
  IFA_F_PERMANENT,
  IFA_F_MANAGETEMPADDR,
  IFA_F_NOPREFIXROUTE,
  IFA_F_MCAUTOJOIN,
  IFA_F_STABLE_PRIVACY,

  RT_SCOPE_UNIVERSE,
  RT_SCOPE_SITE,
  RT_SCOPE_LINK,
  RT_SCOPE_HOST,
  RT_SCOPE_NOWHERE,

  NLA_F_NESTED,
  NLA_F_NET_BYTEORDER,
  NLA_TYPE_MASK,

  IFF_UP,
  IFF_BROADCAST,
  IFF_DEBUG,
  IFF_LOOPBACK,
  IFF_POINTOPOINT,
  IFF_NOTRAILERS,
  IFF_RUNNING,
  IFF_NOARP,
  IFF_PROMISC,
  IFF_ALLMULTI,
  IFF_MASTER,
  IFF_SLAVE,
  IFF_MULTICAST,
  IFF_PORTSEL,
  IFF_AUTOMEDIA,
  IFF_DYNAMIC,
  IFF_LOWER_UP,
  IFF_DORMANT,
  IFF_ECHO,
};
